#!/usr/bin/env python3

import os
import sys
import shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PATH = os.path.join(ROOT, 'deps', 'inkcpp', 'inkcpp_cl')
ARGS = ["inkcpp_cl", "-p"] + sys.argv[1:]
os.execv(PATH, ARGS)
sleep(2)

