EXTERNAL GET_BOOL()
EXTERNAL GET_FLOAT()
EXTERNAL GET_INT()
EXTERNAL GET_UINT()
EXTERNAL GET_STRING()
EXTERNAL SET_BOOL(b)
EXTERNAL SET_FLOAT(f)
EXTERNAL SET_INT(i)
EXTERNAL SET_UINT(i)
EXTERNAL SET_STRING(s)

~ SET_BOOL(true)
~ SET_FLOAT(1.5)
~ SET_INT(-5)
~ SET_UINT(17)
~ SET_STRING("foo")

{GET_BOOL()} {GET_FLOAT()} {GET_INT()} {GET_UINT()} {GET_STRING()}

-> DONE
