var annotated_dup =
[
    [ "ink", "namespaceink.html", [
      [ "compiler", "namespaceink_1_1compiler.html", [
        [ "compilation_results", "structink_1_1compiler_1_1compilation__results.html", "structink_1_1compiler_1_1compilation__results" ]
      ] ],
      [ "runtime", "namespaceink_1_1runtime.html", [
        [ "internal", "namespaceink_1_1runtime_1_1internal.html", [
          [ "callback_base", "classink_1_1runtime_1_1internal_1_1callback__base.html", "classink_1_1runtime_1_1internal_1_1callback__base" ],
          [ "callback", "classink_1_1runtime_1_1internal_1_1callback.html", "classink_1_1runtime_1_1internal_1_1callback" ],
          [ "function_base", "classink_1_1runtime_1_1internal_1_1function__base.html", "classink_1_1runtime_1_1internal_1_1function__base" ],
          [ "function", "classink_1_1runtime_1_1internal_1_1function.html", "classink_1_1runtime_1_1internal_1_1function" ],
          [ "ref_block", "structink_1_1runtime_1_1internal_1_1ref__block.html", "structink_1_1runtime_1_1internal_1_1ref__block" ],
          [ "story_ptr_base", "classink_1_1runtime_1_1internal_1_1story__ptr__base.html", "classink_1_1runtime_1_1internal_1_1story__ptr__base" ],
          [ "get_ith_type", "structink_1_1runtime_1_1internal_1_1get__ith__type.html", null ],
          [ "get_ith_type< 0, Arg, Args... >", "structink_1_1runtime_1_1internal_1_1get__ith__type_3_010_00_01_arg_00_01_args_8_8_8_01_4.html", "structink_1_1runtime_1_1internal_1_1get__ith__type_3_010_00_01_arg_00_01_args_8_8_8_01_4" ],
          [ "constant", "structink_1_1runtime_1_1internal_1_1constant.html", "structink_1_1runtime_1_1internal_1_1constant" ],
          [ "false_type", "structink_1_1runtime_1_1internal_1_1false__type.html", null ],
          [ "true_type", "structink_1_1runtime_1_1internal_1_1true__type.html", null ],
          [ "is_base_of", "structink_1_1runtime_1_1internal_1_1is__base__of.html", null ],
          [ "is_same", "structink_1_1runtime_1_1internal_1_1is__same.html", null ],
          [ "is_same< T, T >", "structink_1_1runtime_1_1internal_1_1is__same_3_01_t_00_01_t_01_4.html", null ],
          [ "is_pointer", "structink_1_1runtime_1_1internal_1_1is__pointer.html", null ],
          [ "is_pointer< T * >", "structink_1_1runtime_1_1internal_1_1is__pointer_3_01_t_01_5_01_4.html", null ],
          [ "remove_cv", "structink_1_1runtime_1_1internal_1_1remove__cv.html", "structink_1_1runtime_1_1internal_1_1remove__cv" ],
          [ "remove_cv< const T >", "structink_1_1runtime_1_1internal_1_1remove__cv_3_01const_01_t_01_4.html", "structink_1_1runtime_1_1internal_1_1remove__cv_3_01const_01_t_01_4" ],
          [ "remove_cv< volatile T >", "structink_1_1runtime_1_1internal_1_1remove__cv_3_01volatile_01_t_01_4.html", "structink_1_1runtime_1_1internal_1_1remove__cv_3_01volatile_01_t_01_4" ],
          [ "remove_cv< const volatile T >", "structink_1_1runtime_1_1internal_1_1remove__cv_3_01const_01volatile_01_t_01_4.html", "structink_1_1runtime_1_1internal_1_1remove__cv_3_01const_01volatile_01_t_01_4" ],
          [ "remove_cvref", "structink_1_1runtime_1_1internal_1_1remove__cvref.html", "structink_1_1runtime_1_1internal_1_1remove__cvref" ],
          [ "is_string", "structink_1_1runtime_1_1internal_1_1is__string.html", null ],
          [ "is_string< T & >", "structink_1_1runtime_1_1internal_1_1is__string_3_01_t_01_6_01_4.html", null ],
          [ "is_string< const T >", "structink_1_1runtime_1_1internal_1_1is__string_3_01const_01_t_01_4.html", null ],
          [ "is_string< const T * >", "structink_1_1runtime_1_1internal_1_1is__string_3_01const_01_t_01_5_01_4.html", null ],
          [ "string_handler", "structink_1_1runtime_1_1internal_1_1string__handler.html", null ],
          [ "string_handler< const T >", "structink_1_1runtime_1_1internal_1_1string__handler_3_01const_01_t_01_4.html", null ],
          [ "string_handler< const T * >", "structink_1_1runtime_1_1internal_1_1string__handler_3_01const_01_t_01_5_01_4.html", null ],
          [ "string_handler< T & >", "structink_1_1runtime_1_1internal_1_1string__handler_3_01_t_01_6_01_4.html", null ],
          [ "function_traits", "structink_1_1runtime_1_1internal_1_1function__traits.html", "structink_1_1runtime_1_1internal_1_1function__traits" ],
          [ "function_traits< R(*)(Args...)>", "structink_1_1runtime_1_1internal_1_1function__traits_3_01_r_07_5_08_07_args_8_8_8_08_4.html", null ],
          [ "function_traits< R(Args...)>", "structink_1_1runtime_1_1internal_1_1function__traits_3_01_r_07_args_8_8_8_08_4.html", "structink_1_1runtime_1_1internal_1_1function__traits_3_01_r_07_args_8_8_8_08_4" ],
          [ "function_traits< R(C::*)(Args...)>", "structink_1_1runtime_1_1internal_1_1function__traits_3_01_r_07_c_1_1_5_08_07_args_8_8_8_08_4.html", null ],
          [ "function_traits< R(C::*)(Args...) const >", "structink_1_1runtime_1_1internal_1_1function__traits_3_01_r_07_c_1_1_5_08_07_args_8_8_8_08_01const_01_4.html", null ],
          [ "function_traits< R(C::*)>", "structink_1_1runtime_1_1internal_1_1function__traits_3_01_r_07_c_1_1_5_08_4.html", null ],
          [ "seq", "structink_1_1runtime_1_1internal_1_1seq.html", "structink_1_1runtime_1_1internal_1_1seq" ],
          [ "concat", "structink_1_1runtime_1_1internal_1_1concat.html", null ],
          [ "concat< seq< I1... >, seq< I2... > >", "structink_1_1runtime_1_1internal_1_1concat_3_01seq_3_01_i1_8_8_8_01_4_00_01seq_3_01_i2_8_8_8_01_4_01_4.html", null ],
          [ "gen_seq", "structink_1_1runtime_1_1internal_1_1gen__seq.html", null ],
          [ "gen_seq< 0 >", "structink_1_1runtime_1_1internal_1_1gen__seq_3_010_01_4.html", null ],
          [ "gen_seq< 1 >", "structink_1_1runtime_1_1internal_1_1gen__seq_3_011_01_4.html", null ],
          [ "always_false", "structink_1_1runtime_1_1internal_1_1always__false.html", null ],
          [ "if_type", "structink_1_1runtime_1_1internal_1_1if__type.html", "structink_1_1runtime_1_1internal_1_1if__type" ],
          [ "if_type< false, T1, T2 >", "structink_1_1runtime_1_1internal_1_1if__type_3_01false_00_01_t1_00_01_t2_01_4.html", "structink_1_1runtime_1_1internal_1_1if__type_3_01false_00_01_t1_00_01_t2_01_4" ],
          [ "enable_if", "structink_1_1runtime_1_1internal_1_1enable__if.html", null ],
          [ "enable_if< true, T >", "structink_1_1runtime_1_1internal_1_1enable__if_3_01true_00_01_t_01_4.html", "structink_1_1runtime_1_1internal_1_1enable__if_3_01true_00_01_t_01_4" ]
        ] ],
        [ "choice", "classink_1_1runtime_1_1choice.html", "classink_1_1runtime_1_1choice" ],
        [ "globals_interface", "classink_1_1runtime_1_1globals__interface.html", "classink_1_1runtime_1_1globals__interface" ],
        [ "list_interface", "classink_1_1runtime_1_1list__interface.html", "classink_1_1runtime_1_1list__interface" ],
        [ "runner_interface", "classink_1_1runtime_1_1runner__interface.html", "classink_1_1runtime_1_1runner__interface" ],
        [ "snapshot", "classink_1_1runtime_1_1snapshot.html", "classink_1_1runtime_1_1snapshot" ],
        [ "story", "classink_1_1runtime_1_1story.html", "classink_1_1runtime_1_1story" ],
        [ "story_ptr", "classink_1_1runtime_1_1story__ptr.html", "classink_1_1runtime_1_1story__ptr" ],
        [ "value", "structink_1_1runtime_1_1value.html", "structink_1_1runtime_1_1value" ]
      ] ]
    ] ],
    [ "AInkRuntime", "class_a_ink_runtime.html", "class_a_ink_runtime" ],
    [ "FInkSnapshot", "struct_f_ink_snapshot.html", "struct_f_ink_snapshot" ],
    [ "FInkVar", "struct_f_ink_var.html", "struct_f_ink_var" ],
    [ "FListFlag", "struct_f_list_flag.html", "struct_f_list_flag" ],
    [ "HInkChoice", "class_h_ink_choice.html", "class_h_ink_choice" ],
    [ "HInkGlobals", "class_h_ink_globals.html", "class_h_ink_globals" ],
    [ "HInkList", "class_h_ink_list.html", "class_h_ink_list" ],
    [ "HInkRunner", "class_h_ink_runner.html", "class_h_ink_runner" ],
    [ "HInkSnapshot", "class_h_ink_snapshot.html", "class_h_ink_snapshot" ],
    [ "HInkStory", "class_h_ink_story.html", "class_h_ink_story" ],
    [ "InkListIter", "struct_ink_list_iter.html", "struct_ink_list_iter" ],
    [ "InkValue", "struct_ink_value.html", "struct_ink_value" ],
    [ "UFuckYou", "class_u_fuck_you.html", null ],
    [ "UInkAsset", "class_u_ink_asset.html", "class_u_ink_asset" ],
    [ "UInkChoice", "class_u_ink_choice.html", "class_u_ink_choice" ],
    [ "UInkList", "class_u_ink_list.html", "class_u_ink_list" ],
    [ "UInkThread", "class_u_ink_thread.html", "class_u_ink_thread" ],
    [ "UInkVarLibrary", "class_u_ink_var_library.html", "class_u_ink_var_library" ],
    [ "UTagList", "class_u_tag_list.html", "class_u_tag_list" ]
];